---
title: "Untitled"
output: html_document
---

```{r}
library(readxl)
NewsResult_medical <- read_excel("../../refinedata/news/medicalnews.xlsx")

NewsResult_dust <- read_excel("../../refinedata/news/dustnews.xlsx")

content_medical <- c()

content_dust <- c()

for( i in 1:nrow(NewsResult_dust)){
   content_dust[length(content_dust)+1]<-NewsResult_dust$본문[i]
}

for( i in 1:nrow(NewsResult_medical)){
   content_medical[length(content_medical)+1]<-NewsResult_medical$본문[i]
}


```



```{r include=FALSE}
library(KoNLP)
library(stringr)
library(dplyr)

# 시스템 사전 로딩(loading)
# useSystemDic()

# 세종 사전 로딩(loading)
useSejongDic()

# NIA 사전 로딩(loading)
# useNIADic()



content_medical <- str_replace_all(content_medical, "\\W", " ")



nouns_medical <- extractNoun(content_medical)



wordcount_medical <- table(unlist(nouns_medical))


     
df_word_medical <- as.data.frame(wordcount_medical, stringsAsFactors = F)





df_word_medical <- rename(df_word_medical,
                  word = Var1,
                  freq = Freq)

df_word_medical <- filter(df_word_medical, nchar(word) >= 2)

df_word_medical <- df_word_medical %>% arrange(desc(freq))



```

```{r include=FALSE}
content_dust <- str_replace_all(content_dust, "\\W", " ")

nouns_dust <- extractNoun(content_dust)

wordcount_dust <- table(unlist(nouns_dust))

df_word_dust <- as.data.frame(wordcount_dust, stringsAsFactors = F)

df_word_dust <- rename(df_word_dust,
                  word = Var1,
                  freq = Freq)

df_word_dust <- filter(df_word_dust, nchar(word) >= 2)

df_word_dust <- df_word_dust %>% arrange(desc(freq))
```

```{r}


figPath = system.file("examples/6.png",package = "wordcloud2")

wordcloud2(df_word_medical, figPath = figPath ,size=0.5)



```

```{r}
figPath = system.file("examples/5.png",package = "wordcloud2")

wordcloud2(df_word_dust, figPath = figPath ,size=1.3)
```

