---
title: "주별 미세먼지농도와 오염물질간 상관관계"
output: html_document
---

```{r}
load('../../refinedata/analysis/analysis_total_Fixed.rda')
library(dplyr)
library(FinCal)
n <- rep(1:157,each = 7)
analysis_total_Fixed$주 <- rep(n[1:1096], 17)
analysis_total_Fixed <- as.data.frame(analysis_total_Fixed)
analysis_total_week <- analysis_total_Fixed %>% 
  group_by(시도, 주) %>% 
  summarise(`평균기온(°C)` = mean(`평균기온(°C)`),
            `평균 풍속(m/s)` = mean(`평균 풍속(m/s)`),
            `평균 현지기압(hPa)` = mean(`평균 현지기압(hPa)`),
            `일강수량(mm)` = mean(`일강수량(mm)`),
            SO2 = geometric.mean(SO2),
            CO = geometric.mean(CO),
            O3 = geometric.mean(O3),
            NO2 = geometric.mean(NO2),
            PM10 = geometric.mean(PM10),
            PM25 = geometric.mean(PM25),
            발병률 = sum(발병률)
            )
```

```{r}
# PM과 오염물질 상관관계 및 산점도

fit <- lm(PM10 ~ SO2, analysis_total_week)
summary(fit)

```

```{r}
plot(PM10 ~ SO2, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```

```{r}
fit <- lm(PM10 ~ NO2, analysis_total_week)
summary(fit)
```

```{r}
plot(PM10 ~ NO2, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```

```{r}
fit <- lm(PM10 ~ O3,analysis_total_week)
summary(fit)
```

```{r}
plot(PM10 ~ O3,analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```


```{r}
fit <- lm(PM10 ~ CO,analysis_total_week)
summary(fit)
```


```{r}
plot(PM10 ~ CO, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```

