---
title: "주별 발병률과 요인들의 상관관계계석"
output: html_document
---

```{r}
load('../../refinedata/analysis/analysis_total_Fixed.rda')
library(dplyr)
library(FinCal)
n <- rep(1:157,each = 7)
analysis_total_Fixed$주 <- rep(n[1:1096], 17)
analysis_total_Fixed <- as.data.frame(analysis_total_Fixed)
analysis_total_week <- analysis_total_Fixed %>% 
  group_by(시도, 주) %>% 
  summarise(`평균기온(°C)` = mean(`평균기온(°C)`),
            `평균 풍속(m/s)` = mean(`평균 풍속(m/s)`),
            `평균 현지기압(hPa)` = mean(`평균 현지기압(hPa)`),
            `일강수량(mm)` = mean(`일강수량(mm)`),
            SO2 = geometric.mean(SO2),
            CO = geometric.mean(CO),
            O3 = geometric.mean(O3),
            NO2 = geometric.mean(NO2),
            PM10 = geometric.mean(PM10),
            PM25 = geometric.mean(PM25),
            발병률 = sum(발병률)
            )
```

```{r}
# 발병률과 

fit <- lm(발병률 ~ PM10, analysis_total_week)
summary(fit)

```

```{r}
plot(발병률 ~ PM10, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```
```{r}
fit <- lm(발병률 ~ PM25, analysis_total_week)
summary(fit)
```
```{r}
plot(발병률 ~ PM25, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))

```


```{r}
fit <- lm(발병률 ~ `평균기온(°C)`,analysis_total_week)
summary(fit)
```


```{r}
plot(발병률 ~ `평균 풍속(m/s)`, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))

```



```{r}
fit <- lm(발병률 ~ `평균 풍속(m/s)`,analysis_total_week)
summary(fit)
```

```{r}
plot(발병률 ~ `평균 풍속(m/s)`,analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```


```{r}
fit <- lm(발병률 ~ `평균 현지기압(hPa)`,analysis_total_week)
summary(fit)
```

```{r}
plot(발병률 ~ `평균 현지기압(hPa)`,analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```



```{r}
fit <- lm(발병률 ~ SO2, analysis_total_week)
summary(fit)
```

```{r}
plot(발병률 ~ SO2, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```


```{r}
fit <- lm(발병률 ~ NO2, analysis_total_week)
summary(fit)
```


```{r}
plot(발병률 ~ NO2, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```

```{r}
fit <- lm(발병률 ~ O3, analysis_total_week)
summary(fit)
```


```{r}
plot(발병률 ~ O3, analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```

```{r}
fit <- lm(발병률 ~ CO, analysis_total_week)
summary(fit)
```

```{r}
plot(발병률 ~ CO,analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```


```{r}
fit <- lm(발병률 ~ `일강수량(mm)`,analysis_total_week)
summary(fit)
```


```{r}
plot(발병률 ~ `일강수량(mm)`,analysis_total_week)
abline(fit, col = 'red')
legend("top", bty="n", cex = 1.3, 
       legend=paste("R2 =", 
                    format(summary(fit)$adj.r.squared, digits=4)))
```




