---
title: "Untitled"
output: html_document
---

##  2016년 분기별 대구,충남,경남

```{r}

load("../../../refinedata/analysis/analysis_total_Fixed.rda")
library(dplyr)


```

```{r}

analysis_2016_quarter1 <- analysis_total_Fixed  %>% filter(substr(일시,1,7)=='2016-01'|substr(일시,1,7)=='2016-02')

analysis_2016_quarter1 <- analysis_2016_quarter1 %>% filter(시도 %in% c("대구","충남","경남")) 

analysis_2016_quarter1 <- analysis_2016_quarter1 %>% dplyr::select(-일시,-시도,-년도,-인구수,-`최다풍향(16방위)`,-발생건수, -`일 최심신적설(cm)`,-`강수 계속시간(hr)`,-`최고기온(°C)`,-`최저기온(°C)`)

analysis_2016_quarter1 <- analysis_2016_quarter1[-1]

analysis_2016_quarter1 <- as.data.frame(scale(analysis_2016_quarter1))


```


```{r}

analysis_2016_quarter2 <- analysis_total_Fixed %>% filter(substr(일시,1,7)=='2016-03'|substr(일시,1,7)=='2016-04'|substr(일시,1,7)=='2016-05')

analysis_2016_quarter2 <- analysis_2016_quarter2 %>% filter(시도 %in% c("대구","충남","경남")) 


analysis_2016_quarter2 <- analysis_2016_quarter2 %>% dplyr::select(-일시,-시도,-년도,-인구수,-`최다풍향(16방위)`,-발생건수, -`일 최심신적설(cm)`,-`강수 계속시간(hr)`,-`최고기온(°C)`,-`최저기온(°C)`)

analysis_2016_quarter2 <- analysis_2016_quarter2[-1]

analysis_2016_quarter2 <- as.data.frame(scale(analysis_2016_quarter2))

```


```{r}

analysis_2016_quarter3 <- analysis_total_Fixed %>% filter(substr(일시,1,7)=='2016-06'|substr(일시,1,7)=='2016-07'|substr(일시,1,7)=='2016-08')

analysis_2016_quarter3 <- analysis_2016_quarter3 %>% filter(시도 %in% c("대구","충남","경남"))

analysis_2016_quarter3 <- analysis_2016_quarter3 %>% dplyr::select(-일시,-시도,-년도,-인구수,-`최다풍향(16방위)`,-발생건수, -`일 최심신적설(cm)`,-`강수 계속시간(hr)`,-`최고기온(°C)`,-`최저기온(°C)`)

analysis_2016_quarter3 <- analysis_2016_quarter3[-1]

analysis_2016_quarter3 <- as.data.frame(scale(analysis_2016_quarter3))

```


```{r}

analysis_2016_quarter4 <- analysis_total_Fixed %>% filter(substr(일시,1,7)=='2016-09'|substr(일시,1,7)=='2016-10'|substr(일시,1,7)=='2016-11')

analysis_2016_quarter4 <- analysis_2016_quarter4 %>% filter(시도 %in% c("대구","충남","경남")) 

analysis_2016_quarter4 <- analysis_2016_quarter4 %>% dplyr::select(-일시,-시도,-년도,-인구수,-`최다풍향(16방위)`,-발생건수, -`일 최심신적설(cm)`,-`강수 계속시간(hr)`,-`최고기온(°C)`,-`최저기온(°C)`)

analysis_2016_quarter4 <- analysis_2016_quarter4[-1]

analysis_2016_quarter4 <- as.data.frame(scale(analysis_2016_quarter4))

```



```{r}

library(corrplot, quietly = TRUE)

corrplot(cor(analysis_2016_quarter1 ), method="circle")

```


```{r}
corrplot(cor(analysis_2016_quarter2 ), method="circle")

```


```{r}
corrplot(cor(analysis_2016_quarter3 ), method="circle")

```


```{r}
corrplot(cor(analysis_2016_quarter4 ), method="circle")

```

```{r}
cor(analysis_2016_quarter1 )

```


```{r}
cor(analysis_2016_quarter2 )

```

```{r}
cor(analysis_2016_quarter3 )

```

```{r}
cor(analysis_2016_quarter4 )

```


```{r}

library(MASS)


fitdata <- analysis_2016_quarter1
fit1 <- lm(발병률 ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)

stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
fit <-  lm(formula = 발병률 ~ PM25 + NO2 + CO + O3, data = analysis_2016_quarter1)

summary(fit)

```



```{r}
fitdata <- analysis_2016_quarter2
fit1 <- lm(발병률 ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)

stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
fit <- lm(formula = 발병률 ~ NO2 + CO + `평균기온(°C)` + PM10 + O3, data = analysis_2016_quarter2)

summary(fit)

```


```{r}
fitdata <- analysis_2016_quarter3

fit1 <- lm(발병률 ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)

stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
 fit <- lm(formula = 발병률 ~ NO2 + `평균 풍속(m/s)` + `평균기온(°C)` + 
    `일강수량(mm)`, 
data = analysis_2016_quarter3)

summary(fit)

```


```{r}
fitdata <- analysis_2016_quarter4
fit1 <- lm(발병률 ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)

stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
fit<- lm(formula = 발병률 ~ NO2 + PM25 + PM10 + O3 + `평균기온(°C)` + 
    CO, data =analysis_2016_quarter4)

summary(fit)

```
