---
title: "Untitled"
output: html_document
---

## 지역별 시계열 시각화

# 전국 일 최심신적설(cm)

```{r}
library(dplyr)
load("../../refinedata/analysis/analysis_total_Fixed.rda")
analysis_total<-analysis_total_Fixed

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```

# 서울 일 최심신적설(cm)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '서울') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '서울 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```

# 부산 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '부산') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '부산 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 대구 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '대구') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '대구 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 인천 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '인천') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '인천 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```

# 광주 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '광주') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '광주 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 대전 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '대전') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '대전 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 울산 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '울산') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '울산 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 세종 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '세종') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '세종 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다
#
```


# 제주 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '제주') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '제주 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 경기 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '경기') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '경기 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 강원 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '강원') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '강원 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 충북 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '충북') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '충북 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 충남 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '충남') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '충남 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 전북 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '전북') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '전북 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 전남 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '전남') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '전남 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 경북 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '경북') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '경북 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```


# 경남 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% filter( 시도 == '경남') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '경남 일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다

```



```{r}
library(dplyr)
library(data.table)
library(ggplot2)


서울 <- analysis_total %>% filter( 시도 == '서울') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
인천 <- analysis_total %>% filter( 시도 == '인천') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
경기 <- analysis_total %>% filter( 시도 == '경기') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))

인천<-인천[-1]
경기<-경기[-1]


data <- cbind(서울,인천,경기)
colnames(data)[2:4]<-c("서울","인천","경기")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +
coord_cartesian(ylim = c(0,20))+
ggtitle("서울 인천 경기 비교")



```

```{r}
광주 <- analysis_total %>% filter( 시도 == '광주') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
대전 <- analysis_total %>% filter( 시도 == '대전') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))


대전<-대전[-1]


data <- cbind(광주,대전)
colnames(data)[2:3]<-c("광주","대전")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,20))+ 
ggtitle("광주 대전")
```


```{r}

대구 <- analysis_total %>% filter( 시도 == '대구') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
충남 <- analysis_total %>% filter( 시도 == '충남') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
경남 <- analysis_total %>% filter( 시도 == '경남') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))

충남<-충남[-1]
경남<-경남[-1]


data <- cbind(대구,충남,경남)
colnames(data)[2:4]<-c("대구","충남","경남")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,20))+ 
ggtitle("대구 충남 경남 비교")



```


```{r}
울산 <- analysis_total %>% filter( 시도 == '울산') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
부산 <- analysis_total %>% filter( 시도 == '부산') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
전남 <- analysis_total %>% filter( 시도 == '전남') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))

부산<-부산[-1]
전남<-전남[-1]


data <- cbind(울산,부산,전남)
colnames(data)[2:4]<-c("울산","부산","전남")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,20))+ 
ggtitle("울산 부산 전남 비교")

```


```{r}
충북 <- analysis_total %>% filter( 시도 == '충북') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
전북 <- analysis_total %>% filter( 시도 == '전북') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))


전북<-전북[-1]


data <- cbind(충북,전북)
colnames(data)[2:3]<-c("충북","전북")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,20))+ 
ggtitle("충북 전북")
```


```{r}
경북 <- analysis_total %>% filter( 시도 == '경북') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
강원 <- analysis_total %>% filter( 시도 == '강원') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))


강원<-강원[-1]


data <- cbind(경북,강원)
colnames(data)[2:3]<-c("경북","강원")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,20))+ 
ggtitle("경북 강원 비교")
```


```{r}
세종 <- analysis_total %>% filter( 시도 == '세종') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))
제주 <- analysis_total %>% filter( 시도 == '제주') %>% group_by(일시) %>% summarise(`일 최심신적설(cm)`= mean(`일 최심신적설(cm)`,na.rm=TRUE))


제주<-제주[-1]


data <- cbind(세종,제주)
colnames(data)[2:3]<-c("세종","제주")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,20))+ 
ggtitle("세종 제주 비교")
```