---
---


## 지역별 시계열 시각화

```{r}
load("../../refinedata/analysis/analysis_total_Fixed.rda")
analysis_total<-analysis_total_Fixed
library(dplyr)

```


# `평균 풍속(m/s)` 전체

```{r}

analysis_sido_day <- analysis_total  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 전체')

#평균 풍속은 계절적 패턴이 미세하다
#전체 시도의 연도추이는 2018년 초까지 미세히 증가하다 감소한다

```

# `평균 풍속(m/s)` 서울

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='서울')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(na.omit(analysis_sido_day[-1]$`평균 풍속(m/s)`),frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 서울')


#서울 연도추이는 미세히 감소하다 2017년 중순부터 감소폭이 증가한다

```

# `평균 풍속(m/s)` 부산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='부산')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 부산')

#부산 연도추이는 일정하다가 2017년 초부터 미세히 증가하다가 2018년 초부터 감소한다

```

# `평균 풍속(m/s)` 대구

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대구')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(na.omit(analysis_sido_day[-1])$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 대구')

#대구 연도추이는 증가하다 2017년부터 미세히 증가하다 2018년 초부터 감소한다

```


# `평균 풍속(m/s)` 인천

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='인천')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 인천')

#인천 연도추이는 감소하다 2017년 초부터 증가하다 
#2017년 가을부터 감소하다 2018년 봄이후 미세히 증가한다

```

# `평균 풍속(m/s)` 광주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='광주')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 광주')

#광주 연도추이는 감소하다 2017년 중순부터 미세히 증가하다 
#2018년 초이후 다시 감소한다

```


# `평균 풍속(m/s)` 대전

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대전')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 대전')


#대전 연도추이는 증가하다 2017년 초 잠시 일정하다 2017년 중순이후 증가하다
#2018 초 부터 다시 감소한다
```

# `평균 풍속(m/s)` 울산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='울산')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 울산')

#울산 연도추이는 증가하다 2018년 부터 감소한다
```

# `평균 풍속(m/s)` 세종

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='세종')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 세종')


#울산 연도추이는 증가하다 2018년 부터 감소한다
```

# `평균 풍속(m/s)` 제주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='제주')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 제주')

#제주 연도추이는 증가하다 2017년 중순부터 감소하다 
#2017년 말 다시 증가하다 2018년 초 감소한다

```

# `평균 풍속(m/s)` 경기

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경기')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 경기')

#경기 연도추이는 약간 증가하다 2016년 중순부터 일정하다 2017년 중순이후 증가하다
#2018년 초부터 다시 감소한다


```

# `평균 풍속(m/s)` 강원

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='강원')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 강원')


#강원 연도추이는 감소하다 2017년 초이후 증가하다
#2018년 초부터 다시 감소한다
```

# `평균 풍속(m/s)` 충북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충북')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 충북')

#충북 연도추이는 증가하다
#2018년 초부터 다시 감소한다


```

# `평균 풍속(m/s)` 충남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충남')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 충남')

#충남 연도추이는 감소하다
#2017년 초부터 미세히 증가하다 
#2018년 초에 일정하다
#2018년 봄이후 다시 감소한다

```

# `평균 풍속(m/s)` 전북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전북')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 전북')

#전북 연도추이는 감소하다
#2016년 미세히 증가하다
#2016년 가을이후 감소하다
#2017년 여름이후 증가하다
#2018년 봄이후 감소한다

```

# `평균 풍속(m/s)` 전남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전남')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 전남')

#전남 연도추이는 일정하다
#2016년 중순이후 급격히 감소하다
#2017년 가을이후 증가하다
#2017년 여름이후 증가하다
#2018년 봄이후 감소한다
```

# `평균 풍속(m/s)` 경북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경북')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 경북')

#전남 연도추이는 증가하다
#2018년 봄이후 감소한다
```

# `평균 풍속(m/s)` 경남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경남')  %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균 풍속(m/s)` 경남')

#전남 연도추이는 일정하다 2016년 여름이후 증가하다
#2018년 봄이후 감소한다

```


```{r}
library(dplyr)
library(data.table)
library(ggplot2)


서울 <- analysis_total %>% filter( 시도 == '서울') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
인천 <- analysis_total %>% filter( 시도 == '인천') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
경기 <- analysis_total %>% filter( 시도 == '경기') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))

인천<-인천[-1]
경기<-경기[-1]


data <- cbind(서울,인천,경기)
colnames(data)[2:4]<-c("서울","인천","경기")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +
coord_cartesian(ylim = c(0,15))+
ggtitle("서울 인천 경기 비교")

#인천 서울 경기 순으로 풍속이 세다


```

```{r}
광주 <- analysis_total %>% filter( 시도 == '광주') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
대전 <- analysis_total %>% filter( 시도 == '대전') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))


대전<-대전[-1]


data <- cbind(광주,대전)
colnames(data)[2:3]<-c("광주","대전")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,15))+ 
ggtitle("광주 대전")

#광주 대전 순으로 풍속이 비슷하다

```


```{r}

대구 <- analysis_total %>% filter( 시도 == '대구') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
충남 <- analysis_total %>% filter( 시도 == '충남') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
경남 <- analysis_total %>% filter( 시도 == '경남') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))

충남<-충남[-1]
경남<-경남[-1]


data <- cbind(대구,충남,경남)
colnames(data)[2:4]<-c("대구","충남","경남")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,15))+ 
ggtitle("대구 충남 경남 비교")

#대구 충남 경남 풍속이 비슷하다


```


```{r}
울산 <- analysis_total %>% filter( 시도 == '울산') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
부산 <- analysis_total %>% filter( 시도 == '부산') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
전남 <- analysis_total %>% filter( 시도 == '전남') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))

부산<-부산[-1]
전남<-전남[-1]


data <- cbind(울산,부산,전남)
colnames(data)[2:4]<-c("울산","부산","전남")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,15))+ 
ggtitle("울산 부산 전남 비교")

#대구 충남 경남 풍속이 비슷하다

```


```{r}
충북 <- analysis_total %>% filter( 시도 == '충북') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
전북 <- analysis_total %>% filter( 시도 == '전북') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))


전북<-전북[-1]


data <- cbind(충북,전북)
colnames(data)[2:3]<-c("충북","전북")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,15))+ 
ggtitle("충북 전북")

#충북 전북 풍속이 비슷하다
```


```{r}
경북 <- analysis_total %>% filter( 시도 == '경북') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
강원 <- analysis_total %>% filter( 시도 == '강원') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))


강원<-강원[-1]


data <- cbind(경북,강원)
colnames(data)[2:3]<-c("경북","강원")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,15))+ 
ggtitle("경북 강원 비교")

#경북 강원 풍속이 비슷하다
# 산에 둘려쌓여 풍속이 셀줄 알았는데 아니었다
```


```{r}
세종 <- analysis_total %>% filter( 시도 == '세종') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))
제주 <- analysis_total %>% filter( 시도 == '제주') %>% group_by(일시) %>% summarise(`평균 풍속(m/s)`= mean(`평균 풍속(m/s)`,na.rm=TRUE))


제주<-제주[-1]


data <- cbind(세종,제주)
colnames(data)[2:3]<-c("세종","제주")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,15))+ 
ggtitle("세종 제주 비교")

#제주가 세종보다 풍속이 세다
#바다에 둘려쌓여 있어인지 제주가 풍속이 세다
```
