---
---


## 지역별 시계열 시각화

```{r}
load("../../refinedata/analysis/analysis_total_Fixed.rda")
analysis_total<-analysis_total_Fixed
library(dplyr)

```


# PM10 전체

```{r}

analysis_sido_day <- analysis_total  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 전체')

# PM10 전체
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 꾸준히 감소하다 2018년 초 이후
# 미세하게 증가하는 추세

```

# PM10 서울

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='서울')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 서울')

# PM10 서울
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 중순 이후 꾸준히 감소

```

# PM10 부산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='부산')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 부산')

# PM10 부산
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년부터 일정하게 유지되다
# 2018년 이후 감소세

```

# PM10 대구

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대구')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 대구')

# PM10 대구
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년부터 감소하다
# 2017년도는 일정, 2018년 다시 감소

```


# PM10 인천

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='인천')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 인천')

# PM10 인천
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 소폭 증가, 말부터 감소하기 시작
# 2018년 초부터 소폭 증가세를 보임

```

# PM10 광주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='광주')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 광주')

# PM10 광주
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 감소세, 2017년부터 증가하기 시작
# 2017년 말부터 2018년 초까지 소폭 감소
# 2018년 중순 이후 증가세

```


# PM10 대전

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대전')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 대전')

# PM10 대전
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 일정하게 유지, 2017년부터 증가하기 시작
# 2017년 말부터 2018년 초까지 감소
# 2018년 중순 이후 완만한 증가세

```

# PM10 울산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='울산')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 울산')

# PM10 울산
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월에 유독 큰 폭의 진동을 보임
# 다른지역에 존재하던 11월의 진동이
# 2018년을 제외하고 잘 보이지 않음
# 2016년 일정하게 유지, 
# 2017년 중순부터 감소세

```

# PM10 세종

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='세종')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 세종')

# PM10 세종
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 완만한 증가세, 
# 2017년 일정하게 유지되다 중순부터 감소,
# 2018년 초 이후 완만하게 증가하는 추세

```

# PM10 제주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='제주')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 제주')

# PM10 제주
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년부터 꾸준히 감소하는 추세 

```

# PM10 경기

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경기')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 경기')

# PM10 경기
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 완만한 증가세, 
# 2017년 감소,
# 2018년 초 이후 완만하게 증가하는 추세


```

# PM10 강원

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='강원')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 강원')

# PM10 강원
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 완만한 증가세, 
# 2017년 초부터 감소,
# 2018년 초 이후 일정하게 유지되는 추세

```

# PM10 충북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충북')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 충북')

# PM10 충북
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 완만한 감소세, 
# 2018년 초 이후 증가하는 추세

```

# PM10 충남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충남')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 충남')

# PM10 충남
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 완만한 증가세 2016년 말부터 감소, 
# 2018년 초 이후 완만하게 증가하는 추세

```

# PM10 전북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전북')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 전북')

# PM10 전북
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 충북과 비슷한 패턴
# 2016년 완만한 증가세 2016년 말부터 감소, 
# 2018년 초 이후 완만하게 증가하는 추세

```

# PM10 전남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전남')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 전남')

# PM10 전남
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 감소세,
# 2017년 초 완만하게 증가하다 말부터 감소,
# 2018년 초 이후 완만하게 증가하는 추세

```

# PM10 경북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경북')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 경북')

# PM10 경북
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 2016년 완만한 증가세, 말에 살짝 감소
# 2017년 일정하게 유지되다 중순부터 급격한 증가세,
# 2018년 완만하게 증가하는 추세

```

# PM10 경남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경남')  %>% group_by(일시) %>% summarise(PM10 = mean(PM10,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = 'PM10 경남')

# PM10 경남
# 4월 최고점, 8월 최저점
# 1년을 주기로 반복되는 패턴
# 3,4월과 11월에 유독 큰 폭의 진동을 보임
# 충남, 전북과 비슷한 패턴
# 2016년 감소세 
# 2018년 초 이후 완만하게 증가하는 추세

```

```{r}
library(dplyr)
library(data.table)
library(ggplot2)


서울 <- analysis_total %>% filter( 시도 == '서울') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
인천 <- analysis_total %>% filter( 시도 == '인천') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
경기 <- analysis_total %>% filter( 시도 == '경기') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))

인천<-인천[-1]
경기<-경기[-1]


data <- cbind(서울,인천,경기)
colnames(data)[2:4]<-c("서울","인천","경기")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +
coord_cartesian(ylim = c(0,250))+
ggtitle("서울 인천 경기 비교")

# 서울, 인천, 경기 모두 패턴과 농도가 비슷함

```

```{r}
광주 <- analysis_total %>% filter( 시도 == '광주') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
대전 <- analysis_total %>% filter( 시도 == '대전') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))


대전<-대전[-1]


data <- cbind(광주,대전)
colnames(data)[2:3]<-c("광주","대전")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,250))+ 
ggtitle("광주 대전")

# 광주, 대전 모두 패턴과 농도가 비슷함

```


```{r}

대구 <- analysis_total %>% filter( 시도 == '대구') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
충남 <- analysis_total %>% filter( 시도 == '충남') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
경남 <- analysis_total %>% filter( 시도 == '경남') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))

충남<-충남[-1]
경남<-경남[-1]


data <- cbind(대구,충남,경남)
colnames(data)[2:4]<-c("대구","충남","경남")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,250))+ 
ggtitle("대구 충남 경남 비교")

# 대구, 충남, 경남 모두 패턴과 농도가 비슷함

```


```{r}
울산 <- analysis_total %>% filter( 시도 == '울산') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
부산 <- analysis_total %>% filter( 시도 == '부산') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
전남 <- analysis_total %>% filter( 시도 == '전남') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))

부산<-부산[-1]
전남<-전남[-1]


data <- cbind(울산,부산,전남)
colnames(data)[2:4]<-c("울산","부산","전남")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,250))+ 
ggtitle("울산 부산 전남 비교")

# 울산, 부산, 전남 모두 패턴과 농도가 비슷함

```


```{r}
충북 <- analysis_total %>% filter( 시도 == '충북') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
전북 <- analysis_total %>% filter( 시도 == '전북') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))


전북<-전북[-1]


data <- cbind(충북,전북)
colnames(data)[2:3]<-c("충북","전북")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,250))+ 
ggtitle("충북 전북")

# 충북, 전북 모두 패턴과 농도가 비슷함

```


```{r}
경북 <- analysis_total %>% filter( 시도 == '경북') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
강원 <- analysis_total %>% filter( 시도 == '강원') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))


강원<-강원[-1]


data <- cbind(경북,강원)
colnames(data)[2:3]<-c("경북","강원")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,250))+ 
ggtitle("경북 강원 비교")

# 경북, 강원 모두 패턴과 농도가 비슷함

```


```{r}
세종 <- analysis_total %>% filter( 시도 == '세종') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))
제주 <- analysis_total %>% filter( 시도 == '제주') %>% group_by(일시) %>% summarise(PM10= mean(PM10,na.rm=TRUE))


제주<-제주[-1]


data <- cbind(세종,제주)
colnames(data)[2:3]<-c("세종","제주")
data <- melt(data,id.vars=1)




ggplot(data=data , aes(x=일시,y=value, colour=variable, group=variable)) + 
geom_line() +  
coord_cartesian(ylim = c(0,250))+ 
ggtitle("세종 제주 비교")

# 세종이 제주에 비해 조금 높은 농도를 보이는 것 같긴
# 하지만 전체적으로 비슷한 패턴
# PM10은 전지역 모두 비슷한 패턴과 농도를 보임

```
