---
title: "일별 시계열분석"
output: html_document
---

```{r}
load("../../refinedata/analysis/analysis_total_Fixed.rda")
library(dplyr)
library(FinCal)
analysis_total <- analysis_total_Fixed

```



# 평균기온(°C)

```{r}

library(forecast)

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '평균기온(°C)')

#평균기온
#여름에는 최고값찍은후 감소 볼록 솟은 형태이다
#2016년까지 완만한 증가 추세이다가  2017년도에 급격히감소하다 2018년도에 서서히 증가


```

# 평균 풍속

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(`평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 풍속(m/s)` , frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '평균 풍속')

#평균풍속
#바람풍속은 일정한 패턴이 없는 것으로 보인다
#2016년에서 2017년 일정하다가 2018년도에 급격히 감소


```


# 평균 현지기압(hPa)

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(`평균 현지기압(hPa)` = mean(`평균 현지기압(hPa)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균 현지기압(hPa)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '평균 현지기압(hPa)')

#평균 현지기압(hPa)은 겨울때 최고점을 찍으며 연도가 흐를수록 올라가는 추세이다
#2016년도 까지는 감소추세이다 2017년도부타 증가추세를 보인다

```


# 일 최심신적설(cm)

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(`일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일 최심신적설(cm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '일 최심신적설')

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다


```

# 일강수량(mm)

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(`일강수량(mm)` = mean(`일강수량(mm)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`일강수량(mm)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '일강수량')

#강수량은 여름에서 초가을까지최고조를 찍는 것으로 보인다.2017년까지 감소추세를 보이다 2017년 여름이후 증가추세를 보인다

```

# 강수 계속시간(hr)

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(`강수 계속시간(hr)` = mean(`강수 계속시간(hr)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`강수 계속시간(hr)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '강수 계속시간')

#강수계속시간은 편차가 크며 2018년은로 갈수록 증가 추세이다

```

# 이산화황

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(SO2 = geometric.mean(SO2))

ts <- ts(analysis_sido_day[-1]$SO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화황')

#이산화황은 겨울에서 봄까지 높은 수치를 기록하다 여름에 떨어졌다가 가을에서 겨울에 오르는 추세이다
#2017년까지 감소 추세이다 2018년도에는 큰 변동이 없다.

```


# 오존

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(O3 = geometric.mean(O3))

ts <- ts(analysis_sido_day[-1]$O3,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '오존')

#오존은 늦봄에 최고치를 직으며 이는 다른 물질에서는 보지 못한 패턴이다 연도별로는 일정해 보인다

```

# 일산화탄소

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(CO = geometric.mean(CO))

ts <- ts(analysis_sido_day[-1]$CO,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '일산화탄소')

#이산화 질소는 겨울철에 높은 수치를 찍으며 변동인 큰편이다. 연도별로는 일정해 보인다

```

# 이산화질소

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(NO2 = geometric.mean(NO2))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소')

#이산화 질소는 겨울철에 높은 수치를 찍으며 변동인 큰편이다. 연도별로는 일정해 보인다

```

# 미세먼지

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(PM10 = geometric.mean(PM10))

ts <- ts(analysis_sido_day[-1]$PM10,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '미세먼지')

#미세먼지 농도는 늦봄시절에 최고치를 찍는 걸로 보인다. 편차는 커보인 것으로 보인다.

```

# 초미세먼지

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(PM25 = geometric.mean(PM25))

ts <- ts(analysis_sido_day[-1]$PM25,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '초미세먼지')

#초미세먼지 농도는 늦봄시절에 최고치를 찍는 걸로 보인다. 편차는 커보인 것으로 보인다. 미세먼지농도보다 조금 앞선 최고치를 이른다


```

# 발생건수

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(발생건수 = sum(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수')

#여름에 감소하는 추세가 보입니다
#2017년 급증하는 것으로 보입니다.

```
# 발병율

```{r}

analysis_sido_day <- analysis_total %>% group_by(일시) %>% summarise(발병률 = sum(발병률))

ts <- ts(analysis_sido_day[-1]$발병률,frequency = 365, start = c(2016,1))


fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발병율')

#여름에 감소하는 추세가 보입니다
#연도별 증가 감소가 반복됩니다


#다음 파일에서 각 요인의 지역별 추세를 탐색합니다. 
```