---
title: "주별 시계열분석"
output: html_document
---


```{r}
load("../../refinedata/analysis/analysis_total_Fixed.rda")
analysis_total <- analysis_total_Fixed
library(dplyr)
library(FinCal)
analysis_day <- analysis_total %>% group_by(substr(일시,1,10)) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE),
                                                             `최저기온(°C)` = mean(`최저기온(°C)`,na.rm=TRUE),
                                                             `최고기온(°C)` = mean(`최고기온(°C)`,na.rm=TRUE),
                                                             `평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE),
                                                             `평균 현지기압(hPa)` = mean(`평균 현지기압(hPa)`,na.rm=TRUE),
                                                             `일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE),
                                                             `일강수량(mm)` = mean(`일강수량(mm)`,na.rm=TRUE),
                                                             `강수 계속시간(hr)` = mean(`강수 계속시간(hr)`,na.rm=TRUE),
                                                             SO2 = geometric.mean(SO2),
                                                             CO = geometric.mean(CO),
                                                             O3 = geometric.mean(O3),
                                                             NO2 = geometric.mean(NO2),
                                                             PM10 = geometric.mean(PM10),
                                                             PM25 = geometric.mean(PM25),
                                                             발생건수 = sum(발생건수),
                                                             발병률 = sum(발병률))




new <- analysis_day[1:7,]
analysis_day <- analysis_day[8:dim(analysis_day)[1],]
collength <- dim(analysis_day)[1]
collength = collength-7
original_summarise <- new %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE),
                                                             `최저기온(°C)` = mean(`최저기온(°C)`,na.rm=TRUE),
                                                             `최고기온(°C)` = mean(`최고기온(°C)`,na.rm=TRUE),
                                                             `평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE),
                                                             `평균 현지기압(hPa)` = mean(`평균 현지기압(hPa)`,na.rm=TRUE),
                                                             `일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE),
                                                             `일강수량(mm)` = mean(`일강수량(mm)`,na.rm=TRUE),
                                                             `강수 계속시간(hr)` = mean(`강수 계속시간(hr)`,na.rm=TRUE),
                                                             SO2 = geometric.mean(SO2),
                                                             CO = geometric.mean(CO),
                                                             O3 = geometric.mean(O3),
                                                             NO2 = geometric.mean(NO2),
                                                             PM10 = geometric.mean(PM10),
                                                             PM25 = geometric.mean(PM25),
                                                             발생건수 = sum(발생건수),
                                                             발병률 = sum(발병률))
  
  


while(collength>0){
  new <- analysis_day[1:7,]
  analysis_day <-  analysis_day[8:dim(analysis_day)[1],]
  collength = collength-7
  new_summarise <- new %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE),
                                                             `최저기온(°C)` = mean(`최저기온(°C)`,na.rm=TRUE),
                                                             `최고기온(°C)` = mean(`최고기온(°C)`,na.rm=TRUE),
                                                             `평균 풍속(m/s)` = mean(`평균 풍속(m/s)`,na.rm=TRUE),
                                                             `평균 현지기압(hPa)` = mean(`평균 현지기압(hPa)`,na.rm=TRUE),
                                                             `일 최심신적설(cm)` = mean(`일 최심신적설(cm)`,na.rm=TRUE),
                                                             `일강수량(mm)` = mean(`일강수량(mm)`,na.rm=TRUE),
                                                             `강수 계속시간(hr)` = mean(`강수 계속시간(hr)`,na.rm=TRUE),
                                                             SO2 = geometric.mean(SO2),
                                                             CO = geometric.mean(CO),
                                                             O3 = geometric.mean(O3),
                                                             NO2 = geometric.mean(NO2),
                                                             PM10 = geometric.mean(PM10),
                                                             PM25 = geometric.mean(PM25),
                                                             발생건수 = sum(발생건수),
                                                             발병률 = sum(발병률))

  original_summarise <- rbind(original_summarise,new_summarise)
  
}

analysis_week<-original_summarise

```



# 평균기온(°C)

```{r}

library(forecast)


ts <- ts(analysis_week$`평균기온(°C)`,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#평균기온/여름에는 최고값찍은후 감소/2016년까지 완만한 증가 추세이다가  2017년도에 급격히감소하다 2018년도에 서서히 증가


```

# 평균 풍속

```{r}


ts <- ts(analysis_week$`평균 풍속(m/s)` , frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#바람풍속은 일정한 패턴이 없는 것으로 보인다
#2018년도에 급격히 감소

```


# 평균 현지기압(hPa)

```{r}



ts <- ts(analysis_week$`평균 현지기압(hPa)`,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#평균 현지기압(hPa)은 겨울때 최고점을 찍으며 연도가 흐를수록 올라가는 추세이다
#2016년도 까지는 감소추세이다 2017년도부타 증가추세를 보인다

```


# 일 최심신적설(cm)

```{r}


ts <- ts(analysis_week$`일 최심신적설(cm)`,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#겨울에 최고점을 찍으며 연도를 거듭할수록 최고점이 높아지고 있다
#평균기온과 연도추세가 반대경향을 따른다


```

# 일강수량(mm)

```{r}



ts <- ts(analysis_week$`일강수량(mm)`,frequency =52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#강수량은 여름에서 초가을까지최고조를 찍는 것으로 보인다.2017년까지 감소추세를 보이다 2017년 여름이후 증가추세를 보인다

```

# 강수 계속시간(hr)

```{r}



ts <- ts(analysis_week$`강수 계속시간(hr)`,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#강수계속시간은 편차가 크며 2018년은로 갈수록 증가 추세이다

```

# 이산화황

```{r}



ts <- ts(analysis_week$SO2,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#이산화황은 겨울에서 봄까지 높은 수치를 기록하다 여름에 떨어졌다가 가을에서 겨울에 오르는 추세이다
#2017년까지 감소 추세이다 2018년도에는 큰 변동이 없다.

```


# 오존

```{r}



ts <- ts(analysis_week$O3,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#오존은 늦봄에 최고치를 직으며 이는 다른 물질에서는 보지 못한 패턴이다 연도별로는 일정해 보인다

```

# 이산화질소

```{r}



ts <- ts(analysis_week$NO2,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#이산화 질소는 겨울철에 높은 수치를 찍으며 변동인 큰편이다. 연도별로는 일정해 보인다

```

# 미세먼지

```{r}



ts <- ts(analysis_week$PM10,frequency =52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#미세먼지 농도는 늦봄시절에 최고치를 찍는 걸로 보인다. 편차는 커보인 것으로 보인다.

```

# 초미세먼지

```{r}



ts <- ts(analysis_week$PM25,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#초미세먼지 농도는 늦봄시절에 최고치를 찍는 걸로 보인다. 편차는 커보인 것으로 보인다. 미세먼지농도보다 조금 앞선 최고치를 이른다


```

# 발생건수

```{r}



ts <- ts(analysis_week$발생건수,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#초미세먼지 농도는 늦봄시절에 최고치를 찍는 걸로 보인다. 편차는 커보인 것으로 보인다. 미세먼지농도보다 조금 앞선 최고치를 이른다


```

# 발병률
```{r}



  ts <- ts(analysis_week$발병률,frequency = 52, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit)

#초미세먼지 농도는 늦봄시절에 최고치를 찍는 걸로 보인다. 편차는 커보인 것으로 보인다. 미세먼지농도보다 조금 앞선 최고치를 이른다


```